stages:
  download:
    cmd: python stages/01_download.py
    deps:
      - stages/01_download.py
    outs:
      - download/Data Excel Files
  build:
    cmd: python stages/02_build.py
    deps:
      - stages/02_build.py
      - download/Data Excel Files
    outs:
      - brick/toxvaldb.parquet
